---
spring:
  application:
    name: "openevolve4j-web"
  main:
    allow-bean-definition-overriding: true
    web-application-type: "reactive"
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.yml
    url: 'jdbc:postgresql://192.168.50.99:5432/evolutions'
    user: postgres
    password: postgres
  r2dbc:
    url: 'r2dbc:postgresql://192.168.50.99:5432/evolutions'
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
---
server:
  port: 7070

---
openevolve:
  webSearch:
    tavilyApiKey:
  liteLlm:
    apiUrl: http://192.168.50.99:4000
    apiKey: sk-9DzvwVXmpXKAcoWTgmZnRg
  path: /home/ubuntu/IdeaProjects/openevolve4j/openevolve4j-core/src/test/resources/openevolve
